[build]
  # Diretório de publicação (onde estão os arquivos estáticos)
  publish = "."
  
  # Comando de build (não necessário para site estático)
  command = "echo 'Site estático - sem build necessário'"

[build.environment]
  # Versão do Node.js
  NODE_VERSION = "18"

# Headers de segurança
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains"

# Cache para assets estáticos
[[headers]]
  for = "/src/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache para imagens
[[headers]]
  for = "*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.webp"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.svg"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

# Redirects
[[redirects]]
  from = "https://www.facenosecodde.com.br/*"
  to = "https://facenosecodde.com.br/:splat"
  status = 301
  force = true

# Configurações de formulário (para Netlify Forms se necessário)
[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = false
  minify = true

[build.processing.html]
  pretty_urls = true

# Configurações de performance
[build.processing.images]
  compress = true